name: Continuous Integration

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-files: 'generated'
          destination-username: 'princemuel'
          destination-repository: 'invoice-web-app'
          destination-branch: 'dev'
          destination-directory: 'generated'
          commit-username: princemuel
          commit-email: vansomecsam@gmail.com
          commit-message: 'docs: update types and schema for graphql'
