name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: './src/lib/generated/'
          destination_repo: 'princemuel/invoice-web-app'
          destination_branch: 'dev'
          destination_folder: '/'
          user_email: 'vansomecsam@gmail.com'
          user_name: 'princemuel'
          commit_message: 'docs: update types and schema for graphql'
